#!/usr/bin/env python3

import os, shutil
folders = ['Downloads', 'Dokumente', 'Musik', 'Videos', 'Programme', 
'Bilder', 'VirtualBox VMs', 'Dropbox']
trash_name = '.Trash-1000'

for folder in folders:
	path = os.path.join(folder, trash_name)
	try:
		if os.path.isfile(path):
			print('Deleting file: ' + str(path) + '.')
			os.unlink(path)
		elif os.path.isdir(path):
			print('Deleting dir: ' + str(path) + '.')
			shutil.rmtree(path)
	except Exception as e:
		print(e)
